### ISSUE TITLE
如何直接把cocosCreater 编译后的 .js 文件的内容复制到 .vue 文件中运行？

### ISSUE THREAD

**Issue by RockYuan** [Hunter-Gu/cc-builder#4]
根据你写的 [Cocos Creator 命令行构建](https://hunter-gu.github.io/personal-blog/2019/06/01/cc-builder/)
> 编译到 Vue
> 在完成上述功能后, 我不禁想能不能将 Cocos Creator 和前端开发的其他库如 Vue 结合起来。 因为想要通过前端库(如 pixijs 等)实现比较炫酷的游戏效果成本还是比较高, 而单纯通过 Cocos Creator 来实现又无法保证较好的代码复用性。
> 
> 仔细观察一下 Cocos Creator 发布后的 .html 文件会发现, 引用了两个 .js 文件(main.js 和 setting.js, cocos 的运行时自然不必多说), 试着直接复制这两个 .js 文件的内容到测试用的 .vue 文件中试试, 发现可以运行, 既然如此我们就可以把 Cocos Creator 编译到 Vue 的 SFC 文件(单文件组件)。

因为我需要把cocosCreater的原生平台编译后的内容放入到vue项目中的其中一个  .vue 模板中，
请问如何直接把cocosCreater 编译后的 .js 文件的内容复制到 .vue 文件中运行？谢谢

**Comment by Hunter-Gu** [comment]
抱歉之前没怎么注意回复晚了。

正如[文档中](https://github.com/Hunter-Gu/cc-builder#%E7%BC%96%E8%AF%91%E5%88%B0-vue)所说，需要在构建路径下添加一个 `vue-template.vue` 模板文件，你没成功的话，大概率是构建路径设置的有问题。

如果还有需要可以回复我，我发个 demo 给你，留下邮箱即可。

这个工具还有很多不足，.vue 文件的模板解析应该用 vue-template-compiler 更合适，但当时做的时候也没有考虑太多。

另外，有一些事情也只是想象中的美好。 Cocos Creator 只允许进行一次初始化，那么 Vue 页面和 Cocos Creator 的页面的切换会是一个比较大的问题。一开始的时候我期望可以实现一个页面中使用两个 Vue 组件就可以嵌套两个 Cocos Creator 场景的情况，也泡汤了。整体感觉 Vue 和 Cocos Creator 两者共存是有这样的需求，使用 iframe 还是最简单，但是性能问题也需要取舍。
